version: '3'

services:

  pgsqldb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: pgsqldb
      POSTGRES_PORT: 5432
    networks:
      - pgsqldb-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - pgsqldb-compose-network

networks:
  pgsqldb-compose-network:
    driver: bridge
